ALTER PROCEDURE [dbo].[GET_LISTINGS_FOR_DAY] @FECHA DATE
AS BEGIN

SELECT  
M.NAME,  
M.IMAGE,  
M.PROTAGONIST,	 
M.DURATION, 
M.SECONDARY, 
M.ID_MOVIE, 
L.FUNTION_DATE,
S.FUNTION_HOUR
FROM MOVIE_SHOW S INNER JOIN MOVIE M 
ON M.ID_MOVIE = S.ID_MOVIE 
JOIN LISTINGS L 
ON S.ID_LISTING = L.ID_LISTINGS
WHERE S.ID_MOVIE IN (SELECT  DISTINCT M.ID_MOVIE  FROM MOVIE_SHOW S INNER JOIN MOVIE M 
ON M.ID_MOVIE = S.ID_MOVIE 
JOIN LISTINGS L 
ON S.ID_LISTING = L.ID_LISTINGS
WHERE CONVERT(Date, S.FUNTION_HOUR) = @FECHA);
END

EXEC GET_MOVIE_SHOW_FOR_DATE '2020-12-19'

select * from MOVIE

ALTER PROCEDURE GET_MOVIE_SHOW_FOR_DATE  @FECHA DATE
AS BEGIN 
SELECT * FROM MOVIE
WHERE ID_MOVIE IN
(SELECT  DISTINCT M.ID_MOVIE  FROM MOVIE_SHOW S INNER JOIN MOVIE M 
ON M.ID_MOVIE = S.ID_MOVIE 
JOIN LISTINGS L 
ON S.ID_LISTING = L.ID_LISTINGS
WHERE CONVERT(Date, S.FUNTION_HOUR) = @FECHA);
END

CREATE PROCEDURE GET_MOVIE_FOR_ID @ID INT
AS BEGIN
SELECT * FROM MOVIE
WHERE ID_MOVIE=@ID 
END 


/* 
AUTOR:			YONI ESPANA
FECHA:			17/12/2020
DESCRIPCION:	OBTIENE LAS FUNCIONES POR PELICULA Y FECHA. 
*/
CREATE PROCEDURE GET_SHOW_FOR_MOVIE_AND_DATE @ID_MOVIE INT, @FECHA DATE
AS BEGIN
SELECT 
S.ID_SHOW,
S.FUNTION_HOUR,
C.NUMBER,
L.FUNTION_DATE
FROM MOVIE_SHOW S JOIN LISTINGS L
ON S.ID_LISTING = L.ID_LISTINGS JOIN
CINEMA C ON S.ID_CINEMA = C.ID_CINEMA
WHERE S.FUNTION_HOUR = @FECHA AND S.ID_MOVIE = @ID_MOVIE
END 

EXEC GET_SHOW_FOR_MOVIE_AND_DATE 10001, '2020-12-19'